"""add review_records

Revision ID: 53816adf617f
Revises: e0f4a7b2c345
Create Date: 2026-09-27 14:35:05.503416

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '53816adf617f'
down_revision: Union[str, Sequence[str], None] = 'e0f4a7b2c345'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('review_records',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('note_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('review_count', sa.Integer(), nullable=False),
    sa.Column('interval_days', sa.Integer(), nullable=False),
    sa.Column('quality', sa.Integer(), nullable=True),
    sa.Column('next_review_at', sa.DateTime(), nullable=False),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['note_id'], ['notes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.uuid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('note_id', name='uq_review_records_note_id')
    )
    op.create_index(op.f('ix_review_records_next_review_at'), 'review_records', ['next_review_at'], unique=False)
    op.create_index(op.f('ix_review_records_note_id'), 'review_records', ['note_id'], unique=False)
    op.create_index(op.f('ix_review_records_user_id'), 'review_records', ['user_id'], unique=False)
    op.drop_index(op.f('ft_notes_title_content'), table_name='notes', mysql_prefix='FULLTEXT', mysql_with_parser='ngram')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ft_notes_title_content'), 'notes', ['title', 'content'], unique=False, mysql_prefix='FULLTEXT', mysql_with_parser='ngram')
    op.drop_index(op.f('ix_review_records_user_id'), table_name='review_records')
    op.drop_index(op.f('ix_review_records_note_id'), table_name='review_records')
    op.drop_index(op.f('ix_review_records_next_review_at'), table_name='review_records')
    op.drop_table('review_records')
    # ### end Alembic commands ###
